Velox_BT_File = 'Sample/BT_testdata.nc'
Velox_VDC_File = 'Velox-VDC.nc'
HALO_IRS_File = 'Sample/IRS_testdata.nc'
MNT_File = 'velox.yaml'
vid_edge_trim = [2, 1, 3, 4] # [Bow, Starboard, Stern, Port]
ERA5_UV_Wind_File = 'Sample/UV_testdata.nc'
DSM_file = 'Sample/DSM_testdata.tif'
Pcs_save_path = 'Sample/Pcs_test.nc'
process_number = 4
low_RAM = False